export const constants = {
  TITLE: 'Title',
  DESCRIPTION: 'Description',
  PRICE: 'Price',
  CATEGORY: 'Category',
  CREATE: 'Create',
  RETIRE_ITEM: 'Retire Item',
  EDIT: 'Edit',
  ADD_TO_CART: 'Add to Cart',
  RETIRED: 'Retired',
  MARK_AS_AVAILABLE: 'Mark as available',
  NEW_ITEM: 'New Item',
  ADD_ITEM: 'Add Item',
  DINNER_DASH: 'Dinner Dash',
  CURRENCY: 'Rs.',
  BACK: 'Back',
  SUMMARY: 'Summary',
  FILTER_HEADING: 'Filter Result by Status',
  ORDER: 'Order',
  MARK_COMPLETED: 'Mark as completed',
  COMPLETED: 'Completed',
  MARK_PAID: 'Mark as paid',
  CANCELLED: 'Cancelled x',
  CANCEL: 'Cancel',
  NAME: 'Name:',
  EMAIL: 'Email:',
  TIME: 'Time:',
  BILL: 'Bill Rs. ',
  DATE: 'Date',
  ITEM: 'Item',
  MY_ORDERS: 'My Orders'
}
